config/routes.rb
V44::Application.routes.draw do

  use_doorkeeper
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    invitations: 'invitations',
    sessions: 'users/sessions'
  }

  get 'party_history/index'

  resources :lawnsign_requests
  resources :volunteers
  resources :photos
  resources :videos
  resources :enewsletters
  resources :tasks
  resources :events

  get 'validate_user' => 'users#validate'

  get 'create_account' => 'users#edit'

  get 'find_riding' => 'riding_addresses#index'


  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root to: 'home#index'
  end


  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'
  
  get 'partyhistory' => 'party_history#index'
  get 'constitution/index' => 'constitution#index'
  get 'constitution/show' => 'constitution#show'
  get 'constitution/:id' => 'constitution#show'
  get 'my_liberal/index'
  get 'volunteer_extended_profile/index'
  get 'volunteer_extended_profile/show'
  get 'donation_limits/index'
  get 'logo/index'
  get 'abc_member/index'
  get 'candidates/index'
  get 'redtrillium/index'
  get 'ontarioliberalfund/index'
  get 'eligibility/index'
  get 'getinvolved/index'
  get 'aboutus/index'
  get 'privacy/index'
  get 'loginhelp/index'
  get 'executive_council/index'
  get 'pla_presidents' => 'pla_presidents#index'
  get 'history/index'
  get 'commissions/index'
  get 'cabinet/index'
  
  get 'donate/index'
  get 'membership/index'
  get 'volunteer/index'
  get 'photo/index'
  get 'news' => 'news#index'
  get 'news/index' => 'news#index'
  get 'news/show' => 'news#show'
  get 'news/:id' => 'news#show'

  get 'platform/index'
  get 'team/index'
  get 'team/show'



  get 'aboutus' => 'aboutus#index'   
  get 'abcmember' => 'abcmember#index'
  get 'aboutdonations' => 'about_donations#index'
  get 'cabinet' => 'cabinet#index'
  get 'commissions' => 'commissions#index'
  get 'candidates' => 'candidates#index'
  get 'constitution' => 'constitution#index'
  get 'contact' => 'contact#index'
  get 'donate' => 'donate#index'
  get 'donationlimits' => 'donationlimits#index'
  get 'eligibility' => 'eligibility#index'
  get 'enewsletter' => 'enewsletter#subscribe'
  get 'executive_council' => 'executive_council#index'
  get 'getinvolved' => 'getinvolved#index'
  get 'history' => 'history#index'
  get 'home' => 'home#index'
  get 'leader' => 'leader#index'

  get 'logo' => 'logo#index'
  get 'membership' => 'membership#index'
  
  get 'mpps' => 'mpps#index'
  get 'mpps/:id' => 'mpps#show'

  get 'ontarioliberalfund' => 'ontarioliberalfund#index'

  get 'platform' => 'platform#index'
  get 'privacy' => 'privacy#index'
  get 'profile' => 'registrations#edit'   
  get 'redtrillium' => 'redtrillium#index'
  get 'register' => 'register#index'
  get 'taxablebenefits' => 'taxable_benefits#index'
  get 'team' => 'team#index'
  get 'team/:id' => 'team#show'
  get 'video' => 'video#index'
  get 'video/:id' => 'video#show'
  get 'volunteerextendedprofile' => 'volunteerextendedprofile#index'

  get 'toolkit' => 'toolkit#index'
  get 'toolkit/:id' => 'toolkit#show'

  resources :petitions do
    post 'add_user', :on => :collection
  end

  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  namespace :admin do

    get '/' => 'home#home'
    resources :documents do
      resources :attachments
    end
    resources :transactions do

    end
    resources :events
    resources :users do
    end

    get 'transactions' => 'transactions#admin_index'
    get 'transaction_scopes/:id' => 'transactions#scopes'
    get 'transaction_user/:id', to: 'transactions#find_user'

    get 'search/users' => 'users#search'
    get 'search/transactions' => 'transactions#search'
    get 'search/events' => 'events#search'
    get 'rapportive' => 'users#rapportive'
    get 'home' => 'home#home'

    get 'contact' => 'home#contact'
    get 'web' => 'home#web'
    get 'lit_samples' => 'home#lit_samples'
  end

  get 'friends' => 'users#friends'

  get '/*.aspx' => redirect('users/registrations#new')


  mount ApplicationAPI => '/api'
end

app/models/event.rb
class Event
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug
  include Mongoid::Search

  field :title, type: String
  field :event_datetime, type: DateTime
  field :location, type: String
  field :address, type: String
  field :address_hint, type: String
  field :email, type: String
  field :contact_person, type: String
  field :phone_number, type: String
  field :summary, type: String
  field :require_register, type: Boolean
  field :member_only, type: Boolean
  field :style, type: String
  field :created_date, type: DateTime
  field :created_ip, type: String
  field :updated_ip, type: String
  field :language, type: String
  field :doc_type, type: Integer
  field :feature_level, type: Integer
  field :ticket_for_sell, type: Boolean
  field :ticket_price_single, type: Integer
  field :ticket_price_pair, type: Integer
  field :ticket_price_table, type: Integer
  field :ticket_price_abc, type: Integer
  field :ticket_price_red_trillium, type: Integer
  field :ticket_price_youth, type: Integer
  field :ticket_price_senior, type: Integer
  field :ticket_price_observer, type: Integer
  field :ticket_price_free, type: Integer
  field :ticket_price_other, type: Integer
  field :ticket_price_option, type: Integer
  field :published, type: Boolean
  field :display_date, type: DateTime
  field :expiry_date, type: DateTime
  field :publish_on_olp, type: Boolean
  field :publish_on_mpp, type: Boolean
  field :publish_on_pla, type: Boolean
  field :publish_on_elect, type: Boolean
  field :partisan, type: Boolean
  field :web_site, type: String
  field :updated_time, type: DateTime
  field :temp_id, type: Integer
  
  belongs_to :user
  belongs_to :riding
  has_many :event_registers

  accepts_nested_attributes_for :user

  slug :title, history: true

  search_in :title, :location, :temp_id

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all.limit(10)
  end

  def new
    @event = Event.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /events
  # POST /events.json
  def create
    success = false
    # API calls need to use temp_id, perhaps they should be in an API controller
    @event = Event.where(id: document_params['id']).first
    if !@event.nil?
      success = @event.update(document_params)
    else
      @event = Document.new(document_params)
      success = @event.save
    end

    respond_to do |format|
      if success
        format.html { redirect_to admin_events_path, notice: 'Event was successfully created.' }
        format.json { render json: 'event saved to mongodb', status: :created }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end
  
  def edit
    respond_to do |format|
      format.js
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to admin_events_url, notice: 'Document was successfully updated.' }
        format.json { head :no_content, status: :success }
        format.js
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to admin_events_url }
      format.json { head :no_content }
      format.js
    end
  end
  
  def set_event
    @event = Event.find params[:id]
  end

  private
  def event_params
    params.require(:event).permit(
        :title,
        :event_datetime,
        :location, 
        :address,
        :address_hint,
        :email,
        :contact_person,
        :phone_number,
    :summary,
    :require_register, 
    :member_only, 
    :style, 
    :created_ip, 
    :updated_ip, 
    :language, 
    :doc_type, 
    :feature_level, 
    :ticket_for_sell, 
    :ticket_price_single, 
    :ticket_price_pair, 
    :ticket_price_table, 
    :ticket_price_abc, 
    :ticket_price_red_trillium, 
    :ticket_price_youth, 
    :ticket_price_senior, 
    :ticket_price_observer, 
    :ticket_price_free, 
    :ticket_price_other, 
    :ticket_price_option, 
    :published, 
    :display_date, 
    :expiry_date, 
    :publish_on_olp, 
    :publish_on_mpp, 
    :publish_on_pla, 
    :publish_on_elect, 
    :partisan, 
    :web_site, 
    :updated_time, 
    :temp_id

    )
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_filter :authenticate_user!, :only => [:create, :update, :destroy]

    respond_to :html, :json

    def index
		  @event_documents = Event.where(:doc_type => 0, :language => @language, :published => true)
                            .gt(event_datetime: DateTime.now)
                            .order_by(:event_datetime.desc)
    end

    def show
    end
    
    def event_params
      params.require(:event).permit(:auth_token, :title, :event_datetime, :location, :address, :address_hint, :email, :contact_person, :phone_number, :summary, :require_register, :member_only, :style, :attached_photo_ids, :attached_video_ids, :attached_pdf_ids, :created_date, :created_ip, :created_user_id, :updated_ip, :language, :doc_type, :feature_level, :ticket_for_sell, :ticket_price_single, :ticket_price_pair, :ticket_price_table, :ticket_price_abc, :ticket_price_red_trillium, :ticket_price_youth, :ticket_price_senior, :ticket_price_observer, :ticket_price_free, :ticket_price_other, :ticket_price_option, :published, :display_date, :expiry_date, :publish_on_olp, :publish_on_mpp, :publish_on_pla,
        :publish_on_elect, :partisan, :temp_id, :riding_id, :web_site, :updated_time)
    end
end

app/helpers/event_helper.rb
module EventHelper
end

app/views/admin/events/_form.html.erb
<%= simple_form_for @event, url: admin_event_path(@event) do |f| %>
    <%= f.input :title %>
    <%= f.input :event_datetime, :input_html => { :class => 'datepicker' } %>
    <%= f.input :location %>
    <%= f.input :address %>
    <%= f.input :address_hint %>
    <%= f.input :email %>
    <%= f.input :contact_person %>
    <%= f.input :phone_number %>
    <%= f.input :summary, as: :text, :input_html => { :class => 'tinymce', :rows => 40, :cols => 80 } %>
    <%= f.input :require_register, as: :boolean %>
    <%= f.input :member_only, as: :boolean %>
    <%= f.input :feature_level %>
    <%= f.input :ticket_for_sell %>
    <%= f.input :ticket_price_single %>
    <%= f.input :ticket_price_pair %>
    <%= f.input :ticket_price_table %>
    <%= f.input :ticket_price_abc %>
    <%= f.input :ticket_price_red_trillium %>
    <%= f.input :ticket_price_youth %>
    <%= f.input :ticket_price_senior %>
    <%= f.input :ticket_price_observer %>
    <%= f.input :ticket_price_free %>
    <%= f.input :ticket_price_other %>
    <%= f.input :ticket_price_option %>
    <%= f.input :published, as: :boolean %>
    <%= f.input :display_date %>
    <%= f.input :expiry_date %>
    <%= f.input :publish_on_olp, as: :boolean %>
    <%= f.input :publish_on_mpp, as: :boolean %>
    <%= f.input :publish_on_pla, as: :boolean %>
    <%= f.input :publish_on_elect, as: :boolean %>
    <%= f.input :partisan %>
    <%#= f.input :riding_id %>
    <%= f.button :submit, 'Save', id: 'save' %>
<% end %>

<%= tinymce %>

app/views/admin/events/edit.js.erb
vex.open({
    content: '<%= j render partial: 'form', event: @event %>',

    afterOpen: function($vexContent) {
        return $vexContent.append($el);
    },

    afterClose: function() {
        return console.log('vexClose');
    }
});

app/views/admin/events/index.html.erb
<%= javascript_include_tag 'searchbox' %>

<div id="search_box">
  <p>Search for user</p>
  <input type="search" id="user_search" data-remote="true" />
</div>

<%= link_to 'Add Event', new_admin_event_path, remote: true %>
<table>
    <thead>
        <tr>
          <th>
            Action
          </th>
          <% Event.attribute_names.each do |a| %>
            <th id='<%= a %>'>
                <%= a.humanize %>
            </th>
          <% end %>
        </tr>
    </thead>
    <% @events.each do |event| %>
        <tr>
          <td>
            <%= link_to 'Edit', edit_admin_event_path(event), remote: true %>
          </td>
          <% Event.attribute_names.each do |a| %>
            <td>
              <%= event[a] %>
            </td>
          <% end %>
        </tr>
    <% end %>
</table>

<script>
    $('#user_search').searchbox({ url: '<%= admin_search_users_path %>.js'});
</script>

app/views/admin/events/new.html.erb
<%= render partial: 'form' %>

app/views/admin/events/new.js.erb
vex.open({
    content: '<%= j render partial: 'form', event: @event %>',

    afterOpen: function($vexContent) {
        return $vexContent.append($el);
    },

    afterClose: function() {
        return console.log('vexClose');
    }
});