config/routes.rb
V44::Application.routes.draw do

  use_doorkeeper
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    invitations: 'invitations',
    sessions: 'users/sessions'
  }

  get 'party_history/index'

  resources :lawnsign_requests
  resources :volunteers
  resources :photos
  resources :videos
  resources :enewsletters
  resources :tasks
  resources :events

  get 'validate_user' => 'users#validate'

  get 'create_account' => 'users#edit'

  get 'find_riding' => 'riding_addresses#index'


  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root to: 'home#index'
  end


  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'
  
  get 'partyhistory' => 'party_history#index'
  get 'constitution/index' => 'constitution#index'
  get 'constitution/show' => 'constitution#show'
  get 'constitution/:id' => 'constitution#show'
  get 'my_liberal/index'
  get 'volunteer_extended_profile/index'
  get 'volunteer_extended_profile/show'
  get 'donation_limits/index'
  get 'logo/index'
  get 'abc_member/index'
  get 'candidates/index'
  get 'redtrillium/index'
  get 'ontarioliberalfund/index'
  get 'eligibility/index'
  get 'getinvolved/index'
  get 'aboutus/index'
  get 'privacy/index'
  get 'loginhelp/index'
  get 'executive_council/index'
  get 'pla_presidents' => 'pla_presidents#index'
  get 'history/index'
  get 'commissions/index'
  get 'cabinet/index'
  
  get 'donate/index'
  get 'membership/index'
  get 'volunteer/index'
  get 'photo/index'
  get 'news' => 'news#index'
  get 'news/index' => 'news#index'
  get 'news/show' => 'news#show'
  get 'news/:id' => 'news#show'

  get 'platform/index'
  get 'team/index'
  get 'team/show'



  get 'aboutus' => 'aboutus#index'   
  get 'abcmember' => 'abcmember#index'
  get 'aboutdonations' => 'about_donations#index'
  get 'cabinet' => 'cabinet#index'
  get 'commissions' => 'commissions#index'
  get 'candidates' => 'candidates#index'
  get 'constitution' => 'constitution#index'
  get 'contact' => 'contact#index'
  get 'donate' => 'donate#index'
  get 'donationlimits' => 'donationlimits#index'
  get 'eligibility' => 'eligibility#index'
  get 'enewsletter' => 'enewsletter#subscribe'
  get 'executive_council' => 'executive_council#index'
  get 'getinvolved' => 'getinvolved#index'
  get 'history' => 'history#index'
  get 'home' => 'home#index'
  get 'leader' => 'leader#index'

  get 'logo' => 'logo#index'
  get 'membership' => 'membership#index'
  
  get 'mpps' => 'mpps#index'
  get 'mpps/:id' => 'mpps#show'

  get 'ontarioliberalfund' => 'ontarioliberalfund#index'

  get 'platform' => 'platform#index'
  get 'privacy' => 'privacy#index'
  get 'profile' => 'registrations#edit'   
  get 'redtrillium' => 'redtrillium#index'
  get 'register' => 'register#index'
  get 'taxablebenefits' => 'taxable_benefits#index'
  get 'team' => 'team#index'
  get 'team/:id' => 'team#show'
  get 'video' => 'video#index'
  get 'video/:id' => 'video#show'
  get 'volunteerextendedprofile' => 'volunteerextendedprofile#index'

  get 'toolkit' => 'toolkit#index'
  get 'toolkit/:id' => 'toolkit#show'

  resources :petitions do
    post 'add_user', :on => :collection
  end

  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  namespace :admin do

    get '/' => 'home#home'
    resources :documents do
      resources :attachments
    end
    resources :transactions do

    end
    resources :events
    resources :users do
    end

    get 'transactions' => 'transactions#admin_index'
    get 'transaction_scopes/:id' => 'transactions#scopes'
    get 'transaction_user/:id', to: 'transactions#find_user'

    get 'search/users' => 'users#search'
    get 'search/transactions' => 'transactions#search'
    get 'search/events' => 'events#search'
    get 'rapportive' => 'users#rapportive'
    get 'home' => 'home#home'

    get 'contact' => 'home#contact'
    get 'web' => 'home#web'
    get 'lit_samples' => 'home#lit_samples'
  end

  get 'friends' => 'users#friends'

  get '/*.aspx' => redirect('users/registrations#new')


  mount ApplicationAPI => '/api'
end

app/models/attachment.rb
class Attachment
  include Mongoid::Document
  include Mongoid::Timestamps
  mount_uploader :pdf, PdfUploader

  field :icon_uri, type: String
  field :title, type: String
  field :description, type: String
  field :database_name, type: String
  field :file_location, type: String
  field :attachment_type, type: Integer
  field :temp_id, type: Integer
  
  #belongs_to :riding
  belongs_to :document

  validates_presence_of :title, :pdf

end

app/controllers/admin/attachments_controller.rb
class Admin::AttachmentsController < Admin::AdminController


  def new
    @document = Document.find_or_create_by(id: params[:document_id])
    @attachment = Attachment.new
    respond_to do |format|
      format.js
    end
  end

  def index
    @attachments = Attachment.all
    @attachment = Attachment.new
  end

  def show
    respond_to do |format|
      format.js {}
    end
  end

  def create
    #if the document doesn't exist how do I pass the parameters
    @attachment = Attachment.new(attachment_params)
    valid = @attachment.valid?
    if valid
      @document = Document.find params[:document_id]
      @document.attachments << @attachment
      valid = @document.save
    end

    if request.xhr? || remotipart_submitted?
      if valid
        render :layout => false, :template => '/admin/attachments/create.js', :status => :ok, :format => :js
      else
        render :layout => false, :template => '/admin/attachments/create.js', :format => :js
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @attachment = Attachment.where(id: params["id"])
    @deleted_attachment_id = @attachment.first.id
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url }
      format.js
    end
  end

  private
   def attachment_params
      params.require(:attachment).permit(
        :icon_uri,
        :language, 
        :upload_date, 
        :title, 
        :description, 
        :place, 
        :database_name,
        :file_location,
        :attachment_type,
        :published,
        :web_site,
        :updated_time,
        :temp_id,
        :pdf,
        :pdf_cache)
    end
end

app/views/admin/attachments/_attachment.html.erb
<% unless attachment.pdf.file.nil? %>
  <li id='<%= attachment.id %>'>
    <%= link_to attachment.title, attachment.pdf.url %>
    <%= link_to "(remove)", admin_document_attachment_path(attachment.document_id, attachment), :method => :delete, :data => { :confirm => 'Are you sure?' }, remote: true  %>
  </li>
<% end %>

app/views/admin/attachments/_form.html.erb
<div class="modal-body">
    <%= simple_form_for [:admin, @document, @attachment], :html => {:multipart => true }, :remote => true do |f| %>
      <%= f.error_notification %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :pdf, as: :file, label: t('add_file') %>
        <%= f.hidden_field :pdf_cache %>
        <br/>
      <%= f.button :submit %>
    <% end %>
</div>

app/views/admin/attachments/create.js.erb
console.log('attachment should have been added from create.js');
<% if @attachment.valid? %>
    vex.close();
    $("#attachments").append("<%= j render @attachment %>");
    $("#document_id").val('<%= @document.id %>');
<% else %>
    $('.error').html('');
    console.log('error fired');
    <% @attachment.errors.each do |key, value| %>
        $('#attachment_<%= key.to_s %>').after('<div class="error"><%= key.to_s + ' ' + value %></div>');
    <% end %>
<% end %>

app/views/admin/attachments/destroy.js.erb
$("#<%= @deleted_attachment_id %>").remove();

app/views/admin/attachments/edit.js.erb
alert('hoeel');

app/views/admin/attachments/index.html.erb
<ul id="attachments">
  <%= render @attachments %>
</ul>

<br />
<div id="form_placeholder"></div>

<%= link_to "Add Pdf", new_admin_document_attachment_path, id: "new_link", remote: true %>

app/views/admin/attachments/new.js.erb
console.log('attachment should open in new.js');
vex.open({

    content: '<%= j (render('form')) %>',

    afterOpen: function($vexContent) {
        //return $vexContent.append($el);
    },

    afterClose: function() {
        return console.log('vexClose');
    }

});