config/routes.rb
V44::Application.routes.draw do

  use_doorkeeper
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    invitations: 'invitations',
    sessions: 'users/sessions'
  }

  get 'party_history/index'

  resources :lawnsign_requests
  resources :volunteers
  resources :photos
  resources :videos
  resources :enewsletters
  resources :tasks
  resources :events

  get 'validate_user' => 'users#validate'

  get 'create_account' => 'users#edit'

  get 'find_riding' => 'riding_addresses#index'


  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root to: 'home#index'
  end


  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'
  
  get 'partyhistory' => 'party_history#index'
  get 'constitution/index' => 'constitution#index'
  get 'constitution/show' => 'constitution#show'
  get 'constitution/:id' => 'constitution#show'
  get 'my_liberal/index'
  get 'volunteer_extended_profile/index'
  get 'volunteer_extended_profile/show'
  get 'donation_limits/index'
  get 'logo/index'
  get 'abc_member/index'
  get 'candidates/index'
  get 'redtrillium/index'
  get 'ontarioliberalfund/index'
  get 'eligibility/index'
  get 'getinvolved/index'
  get 'aboutus/index'
  get 'privacy/index'
  get 'loginhelp/index'
  get 'executive_council/index'
  get 'pla_presidents' => 'pla_presidents#index'
  get 'history/index'
  get 'commissions/index'
  get 'cabinet/index'
  
  get 'donate/index'
  get 'membership/index'
  get 'volunteer/index'
  get 'photo/index'
  get 'news' => 'news#index'
  get 'news/index' => 'news#index'
  get 'news/show' => 'news#show'
  get 'news/:id' => 'news#show'

  get 'platform/index'
  get 'team/index'
  get 'team/show'



  get 'aboutus' => 'aboutus#index'   
  get 'abcmember' => 'abcmember#index'
  get 'aboutdonations' => 'about_donations#index'
  get 'cabinet' => 'cabinet#index'
  get 'commissions' => 'commissions#index'
  get 'candidates' => 'candidates#index'
  get 'constitution' => 'constitution#index'
  get 'contact' => 'contact#index'
  get 'donate' => 'donate#index'
  get 'donationlimits' => 'donationlimits#index'
  get 'eligibility' => 'eligibility#index'
  get 'enewsletter' => 'enewsletter#subscribe'
  get 'executive_council' => 'executive_council#index'
  get 'getinvolved' => 'getinvolved#index'
  get 'history' => 'history#index'
  get 'home' => 'home#index'
  get 'leader' => 'leader#index'

  get 'logo' => 'logo#index'
  get 'membership' => 'membership#index'
  
  get 'mpps' => 'mpps#index'
  get 'mpps/:id' => 'mpps#show'

  get 'ontarioliberalfund' => 'ontarioliberalfund#index'

  get 'platform' => 'platform#index'
  get 'privacy' => 'privacy#index'
  get 'profile' => 'registrations#edit'   
  get 'redtrillium' => 'redtrillium#index'
  get 'register' => 'register#index'
  get 'taxablebenefits' => 'taxable_benefits#index'
  get 'team' => 'team#index'
  get 'team/:id' => 'team#show'
  get 'video' => 'video#index'
  get 'video/:id' => 'video#show'
  get 'volunteerextendedprofile' => 'volunteerextendedprofile#index'

  get 'toolkit' => 'toolkit#index'
  get 'toolkit/:id' => 'toolkit#show'

  resources :petitions do
    post 'add_user', :on => :collection
  end

  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  namespace :admin do

    get '/' => 'home#home'
    resources :documents do
      resources :attachments
    end
    resources :transactions do

    end
    resources :events
    resources :users do
    end

    get 'transactions' => 'transactions#admin_index'
    get 'transaction_scopes/:id' => 'transactions#scopes'
    get 'transaction_user/:id', to: 'transactions#find_user'

    get 'search/users' => 'users#search'
    get 'search/transactions' => 'transactions#search'
    get 'search/events' => 'events#search'
    get 'rapportive' => 'users#rapportive'
    get 'home' => 'home#home'

    get 'contact' => 'home#contact'
    get 'web' => 'home#web'
    get 'lit_samples' => 'home#lit_samples'
  end

  get 'friends' => 'users#friends'

  get '/*.aspx' => redirect('users/registrations#new')


  mount ApplicationAPI => '/api'
end

app/controllers/toolkit_controller.rb
class ToolkitController < ApplicationController
  before_filter :authenticate_user!

  #Admin routes
  def index
    search
    @documents = @documents.limit(5)
    render :layout => 'toolkit_layout'
  end

  def show
    @document = Document.find_by(id: params[:id])
    render :layout => 'toolkit_layout'
  end

  def search
    @documents = Document.toolkit
    params.each do |key, value|
      # target groups using regular expressions
      skip_list = %w(auth_token action controller format scope)
      unless skip_list.include?(key)
        @documents = @documents.where(key => value)
      end
    end
  end
end

app/views/toolkit/index.html.erb
<div class="container">
<% @documents.each do |document| %>

          <!-- <p>ID: <%= document.temp_id %></p> -->
          <div class="listh1 red"><%= link_to document.headline, toolkit_url + '/' + document.id %></div>
          <div class="listh2 grey"><%= link_to document.subtitle, toolkit_path + '/' + document.id %></div>
          <p><%= raw document.introduction %></p>
          <!-- <p>body</h2><%= raw document.body %></p> -->

          <!-- <p class="tiny"><%= document.reference_name %></p>
                        <p class="tiny"><%= document.attached_photo_ids %></p>
                        <p class="tiny"><%= document.attached_video_ids %></p>
                        <p class="tiny"><%= document.attached_pdf_ids %></p> -->

          <!-- <div style="float:left; width:50px;"> -->
          <!-- <a href="http://pantone201.ca/webskins/mpp/pdf/#{<%= document.attached_pdf_ids %>}.pdf" target="_blank"><img alt="Pdf_icon" src="http://pantone201.ca/webskins/css/img/pdf_icon.png"></a>  -->
          <!-- </div>  -->
          <!-- <div style="float:left; clear:right;"><p><a href="http://pantone201.ca/webskins/mpp/pdf/#{<%= document.attached_pdf_ids %>}.pdf" target="_blank">This is the pdf title</a></p><p class="tiny">And this is the description</p></div> -->
          <!-- </div> -->

          <!-- <p class="tiny">Created:<%= document.created_date %></p>  -->
          <!-- <p class="tiny"><%= document.document_date %></p>	-->
          <!-- <p class="tiny"><%= document.language %></p>  -->
          <!-- <p class="tiny"><%= document.published %></p>  -->
          <!-- <p class="tiny"><%= document.image_name %></p>  -->
          <!--  <p class="tiny"><%= document.user_id %></p>    -->
          <!-- <p class="tiny"><%= document.updated_time %></p> -->
          <div class="hrbreake7e6e7">&nbsp;</div>



<% end %>
	  </div> 
	  
	  


	
<div class="pageimageholder">
    <div class="container" ><!--  this will set the content margins left and right -->  
		   <div id="threeupcontainer">
		   <div id="widgetholderleft"><span class="widgeth red"><a href="53167e64386c793e3b040000">CFO Handbook</a></span><div class="widgetsub">This contains all the forms and spreadsheet tools you'll require.</div></div>
		   <div id="widgetholdercenter"><span class="widgeth red"><a href="http://dev.liberalonline.ca/toolkit?customized_category=Samples">Design Inspiration</a></span><div class="widgetsub">See examples of posters,<br>doorcards and campaign training materials and messaging</div></div>
		   <div id="widgetholderright"><span class="widgeth red"><a href="http://dev.liberalonline.ca/toolkit?customized_category=Contact">Contact Info</a></span><div class="widgetsub">Names, phone numbers and email addresses of people who can help.</div></div>
		   </div>
     </div><!-- close container -->
</div><!-- close pageimageholder -->
		   	   <div style="clear:both; display:block;">&nbsp;</div>	

app/views/toolkit/show.html.erb
<div class="content">
  <div class="container">
    <br /><br />
         <h1><%= raw @document.headline %></h1>
         <h2><%= raw @document.subtitle %></h2>
			<!-- <%= image_tag @document.image_url %> -->
               <%= raw @document.body %>

            <div class="hrbreake7e6e7">&nbsp;</div>
              
			  <div>


                        <p class="tiny"><%= @document.author %></p>
                        <p class="tiny"><%= @document.reference_url %></p>
                        <p class="tiny"><%= @document.reference_name %></p>
                        <p class="tiny"><%= @document.attached_photo_ids %></p>
                        <p class="tiny"><%= @document.attached_pdf_ids %></p>
                        <p class="tiny"><%= @document.created_date %></p>
                        <p class="tiny"><%= @document.created_ip %></p>
                        <p class="tiny"><%= @document.document_date %></p>
                        <p class="tiny"><%= @document.updated_time %></p>
						
						<div class="hrbreake7e6e7">&nbsp;</div>
						

            <% unless @document.attachments.nil? %>
                 <% @document.attachments.each do |a| %>
                    <% unless a.pdf.file.nil? %>
                        <div class="<%= a.pdf.file.extension %>" >
                            <h1><%= link_to a.title, a.pdf.url %></h1>
                            <p><%= link_to a.description, a.pdf.url %></p>
                        </div>
                    <% end %>
                 <% end %>
            <% end %>
  </div>
</div>